/// Persona implementations
pub mod architect;
pub mod customer;
pub mod product_manager;
pub mod qa_engineer;
pub mod specialist;
pub use architect::ArchitectPersona;
pub use customer::CustomerPersona;
pub use product_manager::ProductManagerPersona;
pub use qa_engineer::QaEngineerPersona;
pub use specialist::SpecialistPersona;
